# Generated by Django 4.0.6 on 2022-07-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_notes_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='user',
            new_name='owner',
        ),
    ]
