# Generated by Django 4.0.4 on 2022-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('notes', models.CharField(max_length=256)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
